# IMPORTANT: Change the username and paths according to where you save your runs

MODEL_PATH: /home/${username}/
RUNS_DIR: /home/${username}/tmp_guild/runs
# RUNS_DIR: Models will be made available for download later.
# and must be copied locally to the demo server. MODEL_PATH and RUNS_DIR may need to be modified.
# Each subdirectory inside the runs folder is a separate model output directory.
# See the configuration for models above for the unique IDs of the model. e.g. models.pascal.baseline.small points
# to a model subdirectory /home/<${username}>/tmp_guild/runs/841b0d3fed3a41e1ae8cd5e84a9fc233

corruptions:
  all: ['contrast', 'gaussian_noise','shot_noise','impulse_noise','defocus_blur','glass_blur','motion_blur','zoom_blur','snow','frost','fog','brightness','elastic_transform','pixelate','jpeg_compression']
  selected: ['contrast', 'fog', 'frost', 'snow', 'glass_blur', 'defocus_blur', 'pixelate', 'elastic_transform', 'jpeg_compression', 'gaussian_noise']
# SELECTED_CORRUPTIONS = ['contrast', 'brightness','fog', 'snow','frost','gaussian_noise','shot_noise','impulse_noise','defocus_blur','glass_blur','motion_blur','elastic_transform','pixelate','jpeg_compression']


models:
  pascal:
    selections: ['Pascal S', 'Pascal M', 'Pascal L']
    limited_selections: ['Pascal M', 'Pascal L']
    baseline:
      small:
        id: 841b0d3fed3a41e1ae8cd5e84a9fc233
        ap:
          src: 75.87
          contrast: 42.02
      medium:
        id: 8fbf557d7ba34f5b9ac12b73d00dc6a1
        ap:
          src: 83.13
          contrast: 55.81
          fog: 71.74
          frost: 56.28
          snow: 51.77
          glass_blur: 42.17
          defocus_blur: 53.87
          pixelate:  54.52
          elastic_transform: 56.43
          jpeg_compression: 56.17
          gaussian_noise: 48.95
      large:
        id: f17e0b1be899485fa16778ec77df976f
        ap:
          src: 87.48
          contrast: 65.73
    contrast:
      small:
        id: e2aa73f019a6450385042b397d5af612
        ap: 74.75
      medium:
        id: fb30436c44db4dd8a2ef51e6b15e3e88
        ap: 80.27
      large:
        id: 90da0a2471914ae489a7b818fdbde332
        ap: 83.35
    frost:
      small:
        id:
        ap:
      medium:
        id: 29f307e791584f1d8e45d0c9138ff269
        ap: 75.97
      large:
        id: 7760b39317954090a65dbffe63f2199c
        ap: 81.13
    fog:
      small:
        id:
        ap:
      medium:
        id: f17df52dba7940d3ba4aa48d00f7a16e
        ap: 83.79
      large:
        id: 3d1acf8c7a394e16a164f0b4fb81da16
        ap: 86.70
    snow:
      small:
        id:
        ap:
      medium:
        id: ec7bea6717d943dca0a7702f057cea04
        ap: 75.84
      large:
        id: 84157719cc3a4afe9b8fdfa1b20c8224
        ap: 81.14
    brightness:
      small:
        id:
        ap:
      medium:
        id: d589bde8317b4f0f8e3d1755c1fd284f
        ap: 85.97
      large:
        id:
        ap:
    glass_blur:
      small:
        id:
        ap:
      medium:
        id: 0ffe610380874fea9e9103e6bb6adf33
        ap: 64.19
      large:
        id:
        ap:
    defocus_blur:
      small:
        id:
        ap:
      medium:
        id: b1f773df70074d3fb7fb469dfc1da0b1
        ap: 70.95
      large:
        id:
        ap:
    pixelate:
      small:
        id:
        ap:
      medium:
        id: bb465ae43de1434f8f720ed4059c3da6
        ap: 68.35
      large:
        id:
        ap:
    elastic_transform:
      small:
        id:
        ap:
      medium:
        id: ff01778629ea42d9b7275e2a9d1010e8
        ap: 76.82
      large:
        id:
        ap:
    jpeg_compression:
      small:
        id:
        ap:
      medium:
        id: 0ede4639caa64f079cd7275f1862aa76
        ap: 76.20
      large:
        id:
        ap:
    gaussian_noise:
      small:
        id:
        ap:
      medium:
        id: fd11fd52506043c588b5a1bfd04b7613
        ap: 67.39
      large:
        id:
        ap:

  city:
    selections: ['City S', 'City M', 'City L']
    conditions: ['clear', 'all', 'day', 'dusk', 'night']
    baseline:
      small:
        id: 60c825bbcfc4438285cd6818b6206675
        ap:
          src: 36.95
          tgt: 10.47
      medium:
        id: c0ace293d5174dfdba84da1dbbaef39e
        ap:
          src: 44.27
          tgt: 19.96
      large:
        id:  43b7af63ce6f4f1aaf3a9cc39dae4b41
        ap:
          src: 46.81
          tgt: 30.94
    adapted:
      small:
        id: 14550a6c6c564d318eb84395c9991d44
        ap:
          src: 32.43
          tgt: 31.12
      medium:
        id: fd0dfe5d643448f392f2f793d3a52b21
        ap:
          src: 40.41
          tgt: 43.90
      large:
        id: b18bbc315a234bb3ae0d3dcacc0f6146
        ap:
          src: 40.60
          tgt: 56.88

  street:
    selections: ['Street S', 'Street M', 'Street L']
    conditions: ['clear', 'foggy']
    baseline:
      small:
        id: 400928444d0d4c27bb03c1fa9a9ad021
        ap:
          src: 49.43
          tgt: 23.85
      medium:
        id: 589d313a176546829a662f8f2eae890a
        ap:
          src: 52.36
          tgt:  41.88
      large:
        id: 07af4d9130954f98acd03e2ea1d0f3e7
        ap:
          src: 63.41
          tgt: 42.48 # verify
    adapted:
      small:
        id: decab02b9d8e4b80b38e6ea63a7877dd
        ap:
          src: 48.40
          tgt: 80.89
      medium:
        id: 3b3df2bda972405597c9f4b40ee8da63
        ap:
          src: 52.07
          tgt: 84.02
      large:
        id: 3a746c397815421da12ad73ed4828f19
        ap:
          src:
          tgt: 88.03

data:
  pascal:
    SOURCE_DIR: /home/${username}/data/voc_yolo/VOC2007/images/test_demo
    test:
      path: /home/${username}/data/voc_yolo/VOC2007/images/test_demo
  city:
    all:
      path: /home/${username}/data/rain_yolo/images/test_demo/
    clear:
      path: /home/${username}/data/city_yolo/images/val/
    day:
      path: /home/${username}/data/rain_yolo/images/test-1
    dusk:
      path: /home/${username}/data/rain_yolo/images/test-4
    night:
      path: /home/${username}/data/rain_yolo/images/test-5

  street:
    clear:
      path: /home/${username}/data/street_yolo/images/test-clear/
    foggy:
      path: /home/${username}/data/street_yolo/images/test-fog/



